/* =====================================================================
   Content (SAMPLE: replace with your real posts, services and events)
   ===================================================================== */
const SERVICES = [
  { id: 'tech', icon: 'chart', en: ['Tech Help & Smart Buying', 'Get unstuck with phones, apps and computers, and choose the right device for your money.'], so: ['Caawinta Tiknolojiyada & Iibsashada Caqliga leh', 'Ka baxsan dhibaatooyinka taleefannada, abka iyo kombuyuutarrada, oo dooro aaladda ku haboon lacagtaada.'], who: { en: 'For anyone with a tech problem or a purchase to make', so: 'Loogu talagalay qof kasta oo leh dhibaato tiknolojiyo ama iibsasho' }, note: { en: 'No physical repairs, hardware problems need a repair shop.', so: 'Dayactir jireed ma jiro, dhibaatooyinka qalabka waxay u baahan yihiin dukaanka dayactirka.' } },
  { id: 'creator', icon: 'video', en: ['Creator Growth Coaching', 'Plan your content, grow your channel and build income from what you create.'], so: ['Tababarka Kobcinta Abuureyaasha', 'Qorshee nuxurkaaga, kobci kanaalkaaga oo dhis dakhli ka yimaada waxa aad abuurto.'], who: { en: 'For people making videos', so: 'Loogu talagalay dadka sameeya muuqaallada' }, note: { en: 'No guaranteed results, growth depends on many things.', so: 'Natiijo la damaanad qaaday ma jirto, kobacu wuxuu ku xiran yahay arrimo badan.' } },
  { id: 'business', icon: 'spark', en: ['Business Online Growth', 'Get found online and turn attention into customers with a simple, practical plan.'], so: ['Kobcinta Ganacsiga Online-ka', 'Ka muuqo online-ka oo u beddel dareenka macaamiil adigoo adeegsanaya qorshe fudud oo wax ku ool ah.'], who: { en: 'For small businesses', so: 'Loogu talagalay ganacsiyada yaryar' }, note: { en: 'No guaranteed results, sales depend on many things.', so: 'Natiijo la damaanad qaaday ma jirto, iibku wuxuu ku xiran yahay arrimo badan.' } },
  { id: 'safety', icon: 'cap', en: ['Account Audit & Online Safety', 'Check how safe your accounts are, close the gaps and learn to avoid scams.'], so: ['Hubinta Akoonnada & Badbaadada Online-ka', 'Hubi sida ay u ammaan yihiin akoonnadaada, xir godadka oo baro sida looga fogaado khayaanada.'], who: { en: 'For anyone who uses social media, email or mobile money', so: 'Loogu talagalay qof kasta oo isticmaala baraha bulshada, email ama lacagta mobilka' }, note: { en: 'No account recovery, I can explain the official recovery steps.', so: 'Soo celinta akoonka ma jirto, waxaan sharaxi karaa tallaabooyinka rasmiga ah.' } },
];
const ADS = [];   // partner ads for the blog pages, managed in Dashboard → Content → Partner ads
const MEDIA = [];   // Your videos, interviews, podcasts and articles, add them in Dashboard → Content → Media (YouTube thumbnails are automatic).
const GUIDES = {};   // guides (blog posts) linked to each service, filled from the dashboard
const PROOF = [      // Your own work. Facts taken from engyuyu.com: add real client results in Dashboard → Content → Proof.
  { id: 'p1', metric: '1M+', en: ['A community built on trust', 'Grew an audience of over a million people across YouTube, Facebook, TikTok and Instagram by teaching technology in plain language.'], so: ['Bulsho ku dhisan aamin', 'Waxaan kobciyay dhagaystayaal ka badan hal milyan oo ku kala jira YouTube, Facebook, TikTok iyo Instagram anigoo tiknolojiyada ku sharaxaya af fudud.'] },
  { id: 'p2', metric: 'Hundreds', en: ['Educational videos', 'Practical videos on smartphones, AI, digital safety and online skills, in Somali and English.'], so: ['Muuqaallo waxbarasho', 'Muuqaallo wax ku ool ah oo ku saabsan taleefannada, AI, badbaadada dijitaalka iyo xirfadaha online-ka, Soomaali iyo Ingiriisi.'] },
  { id: 'p3', metric: 'Millions', en: ['Live events & programs', 'Tech talks, workshops and community programs that have reached millions of people.'], so: ['Dhacdooyin toos ah & barnaamijyo', 'Hadallo tiknolojiyo, aqoon-isweydaarsiyo iyo barnaamijyo bulsho oo gaaray malaayiin qof.'] },
  { id: 'p4', metric: '4+', en: ['Brand collaborations', 'Education-led partnerships with Taran, Keshflip, Amka and Sanguuni.'], so: ['Wada-shaqayn shirkado', 'Lammaanayaal waxbarasho ku dhisan oo lala yeeshay Taran, Keshflip, Amka iyo Sanguuni.'] },
];
const TESTIMONIALS = [];   // Add client testimonials in Dashboard → Content → Testimonials; the section appears automatically.

const EVENTS = [   // DEMO events (sample photos in /assets/samples). Replace them in Dashboard → Content → Events.
  { feature: true, type: 'conference', icon: 'mic', tag: ['Keynote', 'Hadal Muhiim ah'], date: '2026-11-20', place: 'Venue to be announced', images: ['/assets/samples/event-1.svg', '/assets/samples/event-2.svg', '/assets/samples/event-3.svg', '/assets/samples/event-4.svg'],
    article: { en: 'DEMO STORY. A full-day gathering for builders, creators and brands shaping the Somali digital future.\n\nThis is where the highlights of your event go: the topic of your keynote, the questions from the audience, the people you met. Add 1–4 photos in the dashboard, the first one is the cover.', so: 'TIJAABO. Maalin buuxda oo loogu talagalay dhisayaasha, abuureyaasha iyo shirkadaha qaabeynaya mustaqbalka dijitaalka Soomaaliyeed.\n\nHalkan ayaa lagu qoraa xusuusta dhacdadaada.' },
    en: ['Somali Tech & Creators Summit', 'A full-day gathering for builders, creators and brands shaping the Somali digital future.'], so: ['Shirka Tiknolojiyada & Abuureyaasha Soomaaliyeed', 'Maalin buuxda oo loogu talagalay dhisayaasha, abuureyaasha iyo shirkadaha qaabeynaya mustaqbalka dijitaalka Soomaaliyeed.'] },
  { type: 'workshop', icon: 'cap', tag: ['Workshop', 'Aqoon-isweydaarsi'], date: '2026-12-05', place: 'Online', images: ['/assets/samples/event-3.svg', '/assets/samples/event-1.svg'],
    article: { en: 'DEMO STORY. A hands-on workshop on using AI tools to plan, write and edit faster.\n\nDescribe what participants will learn and what to bring.', so: 'TIJAABO. Aqoon-isweydaarsi wax ku ool ah oo ku saabsan isticmaalka qalabka AI si loo qorsheeyo, loo qoro loona tafatiro degdeg.' },
    en: ['AI for Content Creators', 'A hands-on workshop on using AI tools to plan, write and edit faster.'], so: ['AI loogu talagalay Abuureyaasha', 'Aqoon-isweydaarsi wax ku ool ah oo ku saabsan isticmaalka qalabka AI si loo qorsheeyo, loo qoro loona tafatiro degdeg.'] },
  { type: 'media', icon: 'video', tag: ['Media', 'Warbaahin'], date: '2027-01-15', place: 'YouTube', images: ['/assets/samples/event-2.svg'],
    article: { en: '', so: '' },
    en: ['The Yuyu Tech Show: Season launch', 'New season of interviews and deep dives with founders and engineers.'], so: ['Bandhigga Yuyu Tech: Bilowga xilli cusub', 'Xilli cusub oo wareysiyo iyo falanqayn qoto dheer ah oo lala yeeshay aasaasayaasha iyo injineerrada.'] },
  { type: 'conference', icon: 'mic', tag: ['Conference', 'Shir'], date: '2026-09-12', place: 'Demo City', images: ['/assets/samples/event-1.svg', '/assets/samples/event-2.svg', '/assets/samples/event-3.svg', '/assets/samples/event-4.svg'],
    article: { en: 'DEMO STORY. How a past conference looks on your site: four photos, the key moments of your talk and what the audience asked.\n\nWrite two or three short paragraphs about what happened.', so: 'TIJAABO. Sida shir hore ugu muuqdo goobtaada.' },
    en: ['Demo conference keynote', 'A demo past conference with four photos. Replace it with your own event.'], so: ['Hadal shir tijaabo ah', 'Shir hore oo tijaabo ah oo leh afar sawir.'] },
  { type: 'panel', icon: 'mic', tag: ['Panel', 'Guddi'], date: '2026-07-03', place: 'Online', images: ['/assets/samples/event-3.svg', '/assets/samples/event-1.svg'],
    article: { en: 'DEMO STORY. A panel discussion about digital safety for communities.', so: 'TIJAABO. Wada-hadal guddi ah oo ku saabsan badbaadada dijitaalka.' },
    en: ['Demo panel on digital safety', 'A demo panel with two photos.'], so: ['Guddi tijaabo ah oo ku saabsan badbaadada dijitaalka', 'Guddi tijaabo ah oo laba sawir leh.'] },
  { type: 'attended', icon: 'cap', tag: ['Attended', 'Ka qaybgalay'], date: '2026-05-18', place: 'Demo Expo', images: ['/assets/samples/event-4.svg'],
    article: { en: '', so: '' },
    en: ['Attended a tech expo', 'A demo event with a single cover photo.'], so: ['Ka qaybgal bandhig tiknolojiyo', 'Dhacdo tijaabo ah oo hal sawir leh.'] },
];

const POSTS = [
  { cat: 'ai', min: 6, date: '2026-09-28', thumb: '/assets/samples/post-1.svg', href: '/blog/how-ai-is-changing-the-way-somali-creators-work', video: true, en: ['How AI is changing the way Somali creators work', 'Practical AI workflows for scripting, translation and editing you can start using today.'], so: ['Sida AI u beddelayso shaqada abuureyaasha Soomaaliyeed', 'Habab AI oo wax ku ool ah oo qorista qoraalka, tarjumaadda iyo tafatirka ah oo maanta bilaabi karto.'] },
  { cat: 'gadgets', min: 5, date: '2026-09-14', thumb: '/assets/samples/post-2.svg', href: '/blog/best-budget-phones-for-creators', en: ['Best budget phones for creators in 2026', 'Camera, battery and value compared, what to buy and what to skip.'], so: ['Taleefannada ugu fiican ee qiimaha jaban ee abuureyaasha 2026', 'Kamarada, batariga iyo qiimaha oo la is barbar dhigay, waxa la iibsado iyo waxa laga tago.'] },
  { cat: 'growth', min: 8, date: '2026-08-30', thumb: '/assets/samples/post-3.svg', href: '/blog/from-zero-to-100k-channel-growth-playbook', video: true, en: ['From 0 to 100K: a channel growth playbook', 'The content pillars, posting rhythm and analytics habits behind steady growth.'], so: ['0 ilaa 100K: buug-gacmeed koboca kanaalka', 'Tiirarka nuxurka, xawaaraha daabacaadda iyo caadooyinka falanqaynta ee ka danbeeya kobocka joogtada ah.'] },
  { cat: 'dev', min: 7, date: '2026-08-12', en: ['Start coding in Somali: a beginner roadmap', 'A free, step-by-step path from first line of code to your first project.'], so: ['Ku bilow barnaamijka Soomaali: khariidad bilow ah', 'Waddo bilaash ah oo tallaabo-tallaabo ah laga bilaabo xariiqda koowaad ee koodka ilaa mashruucaaga koowaad.'] },
  { cat: 'ai', min: 4, date: '2026-07-25', en: ['5 free AI tools every student should know', 'Study smarter with tools that cost nothing and save hours every week.'], so: ['5 qalab AI ah oo bilaash ah oo arday kasta ogaado', 'Ku baro si caqli badan qalab aan waxba kaa qaadin oo saacado ku badbaadiya toddobaad kasta.'] },
  { cat: 'growth', min: 6, date: '2026-07-04', en: ['How brands should work with creators', 'Briefs, budgets and trust: a short guide to partnerships that actually perform.'], so: ['Sida shirkaduhu ula shaqeeyaan abuureyaasha', 'Tilmaamo, miisaaniyad iyo aamin: hage kooban oo ku saabsan lammaanaysi dhabta u shaqeeya.'] },
];
const CATS = { all: ['All', 'Dhammaan'], ai: ['AI', 'AI'], gadgets: ['Gadgets', 'Aalado'], dev: ['Development', 'Horumarin'], growth: ['Digital Growth', 'Koboc Dijitaal'] };

